version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
