
services:
  db:
    image: postgres:latest
    container_name: nestjs_db
    restart: always
    environment:
      POSTGRES_USER: vuducvi
      POSTGRES_PASSWORD: vuducvi
      POSTGRES_DB: coffee_shop
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'ps_isready -U vuducvi -d coffee_shop']
      interval: 1m
      timeout: 5s
      retries: 10
    networks:
      - coffee_shop

  backend:
    image: node:20-alpine
    container_name: nestjs_backend
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    command: ['npm', 'run', 'start:dev']
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - coffee_shop
    environment:
      - DB_HOST=host.docker.internal

networks:
  coffee_shop:

